apiVersion: designate.openstack.org/v1beta1
kind: Designate
metadata:
  name: designate
spec:
  secret: osp-secret
  serviceUser: designate
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseAccount: designate
  rabbitMqClusterName: rabbitmq
